name: dart_neuralnet
version: 0.1.0
author: SlightlyCyborg
description: A neural net framework
homepage: https://github.com/SlightlyCyborg/dart-neuralnet
dependencies:
  browser: any
  csvparser: any
